# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: xenial
sudo: false
language: r

# Should warnings be treated as errors? The default value for this
# is true. This needs to be set to false.
warnings_are_errors: false

# Which R version should be used?
# release = Latest minor release version.
r: release

cache:
  packages: true

apt_packages:
  - libgdal-dev
  - libudunits2-dev

git:
  depth: false

r_packages:
  - gapminder
  - ggthemes
  - maps
  - RColorBrewer
  - rnaturalearth
  - rnaturalearthdata
  - rsconnect
  - shiny
  - shinyAce
  - survminer
  - survival
  - tidyverse

deploy:
  provider: script
  script: R -f deploy.R
