# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: xenial
language: r
cache: packages
sudo: false
r: release

addons:
  apt:
    packages:
      - libgdal-dev
      - libudunits2-dev

git:
  depth: false

r_packages:
  - ggthemes
  - maps
  - RColorBrewer
  - rnaturalearth
  - rnaturalearthdata
  - rsconnect
  - shiny
  - shinyAce
  - survminer
  - survival
  - tidyverse

deploy:
  provider: script
  script: R -f deploy.R
