# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: xenial
language: r
cache: packages
sudo: false
warnings_are_errors: false
r: release

git:
  depth: false

r_packages:
  - rsconnect

deploy:
  provider: script
  script: R -f deploy.R
